### ISSUE TITLE
Phone number field accepting any random number.[Sign-up]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#10]
1. Enter any random string in the phone number field.

Expected result- In the Phone number field only accepts valid numbers. 

Actual result-Accepting any random string in the phone number field and accepting incomplete phone numbers also.
example- Accepting symbols, alphabets, dada5$7567#7, 428/587/825/368.
             
Check here-https://nimb.ws/KAuhp0

**Comment by rohit-metagauss** [comment]
@Bhagyashrimane This is fixed and deployed. Please test this.

**Comment by Bhagyashrimane** [comment]
Verified.
