### ISSUE TITLE
Add icons for all the fields.[Form-build]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#100]
Please add the icons for all the fields on the form build page.
e.g.
![image](https://user-images.githubusercontent.com/77260614/132093393-d5186801-88fb-4aa8-9fd8-5eefa6c3240d.png)

**Comment by mJawed** [comment]
1. Text  <i class=" class="material-icons"">text_fields</i>
2. Date  <i class=" class="material-icons"">date_range</i>
3. Phone  <i class=" class="material-icons"">phone</i>
4. Currency  
5. Price  <i class=" class="material-icons"">attach_money</i>
6. Name  <i class=" class="material-icons"">person</i>
7. Email  <i class=" class="material-icons"">mail</i>
8. Radio  <i class=" class="material-icons"">radio_button_checked</i>
9. checkbox  <i class=" class="material-icons"">check_circle</i>
10. rating <i class=" class="material-icons"">grade</i>
11. Number <i class=" class="material-icons"">numbers</i>
12. Address <i class=" class="material-icons"">place</i>
13. Website <i class=" class="material-icons"">public</i>

**Comment by mJawed** [comment]
Added all icons.

**Comment by Bhagyashrimane** [comment]
Number field and page break field not looking proper.

**Comment by charan-singh05** [comment]
Icons for Calendar and Time controls on Form builder page are same. Time's icon needs to be updated.

**Comment by mJawed** [comment]
Time icon updated.

**Comment by charan-singh05** [comment]
Issue fix verified.
