### ISSUE TITLE
User page-Invited user on organization page email field showing editable.[Manage-work-space]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#101]
When editing the invited user,
On staging-email field showing not editable
On Revamp- email field showing editable. That's why able to change the email and got a mail that the user switched from one email user to another email user.

**Comment by hunny-metagauss** [comment]
fixed

**Comment by Bhagyashrimane** [comment]
working fine.
