### ISSUE TITLE
On Roles page, Permission checkboxes showing in blue colors.[Manage-work-space]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#102]
1. Click on one of the organizations.
2. click on the Roles page.
3. Add a new role or edit the existing role.

Actual result- The checkboxes of the permission modules on the Role pages showing blue colored.
Check here-
![image](https://user-images.githubusercontent.com/77260614/132331454-7d546245-9e1a-49ec-a6fd-d47c7c1dfeba.png)

**Comment by mJawed** [comment]
Fixed.

**Comment by charan-singh05** [comment]
Issue fix verified.
