### ISSUE TITLE
Login page- password field size changes.[Login-page]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#103]
1. Open the login page.
2. Observe the password field.

Check here-
![image](https://user-images.githubusercontent.com/77260614/132333890-4e75a748-d1b4-4287-b9f8-75ab370c86c6.png)

**Comment by mJawed** [comment]
Fixed.

**Comment by Bhagyashrimane** [comment]
Looking fine.
