### ISSUE TITLE
Number field, icon and label alignment not proper and page break field label not showing .[Form-build]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#105]
A.
1. Form build page
2. Controls and observe the fields.
3. Basic controls
Alignment of Number fields icon and label not proper.
Check here-
![image](https://user-images.githubusercontent.com/77260614/132483251-c7fafcba-32ed-493d-829b-02424034563a.png)

B. Page break field label and icon not showing. in Layout controls
Check here-
![image](https://user-images.githubusercontent.com/77260614/132484039-8f3cd4f2-9880-4d8a-8eb0-866277362681.png)

**Comment by mJawed** [comment]
its working fine it my local 

@rohit-metagauss could you please check it at your end.

**Comment by charan-singh05** [comment]
Jawed- this is still an issue.

Also, when we click on "Collect Payment" check box, the subsequent entry boxes for prices are all having alignment issues.

**Comment by mJawed** [comment]
@rohit-metagauss  As discussed, please check it at the time of deploment.

**Comment by charan-singh05** [comment]
Closing this now for re-test on staging deployment. If issue is not resolved even on Staging, then this has to be re-visited.
