### ISSUE TITLE
For page break- Popover body not able to open properly.[Form-build]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#106]
1. Form build page
2. drag and drop page -break field.
3. observe ellipsis.
Page break field, Popover body 3 dots ellipsis not able to click. Because not able to hover proper control on that ellipsis (3 dots).

**Comment by mJawed** [comment]
Removed ellipsis

**Comment by Bhagyashrimane** [comment]
Ellipsis is not removed still showing with page breaks.

**Comment by mJawed** [comment]
please checked now, changes were not deployed.

**Comment by charan-singh05** [comment]
Page break still not working properly. But it will be tracked over different issue. Closing this one.
