### ISSUE TITLE
When control is resized to the biggest size then Make Bigger or Make smaller not appearing faded out.[Form-build]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#107]
1. When control is resized to the biggest possible size either via contextual menu or via left side panel options, the contextual option for "Make Bigger" not appearing to fade out.
2. When control is resized to the smallest possible size either via contextual menu or via left side panel options, the contextual option for "Make Smaller" not appearing to fade out.

**Comment by Bhagyashrimane** [comment]
Still issue appearing.

**Comment by mJawed** [comment]
It's working fine at my end, could you please retest it.

**Comment by charan-singh05** [comment]
Issue fix verified.
