### ISSUE TITLE
Publish-page, Submit button label color is not visible properly.[Form-publish]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#108]
1. Form build.
2. Drag and drop some fields.
3. Click on publish

Actual result- Submit button label not visible when hover over the button then shows the Label.

**Comment by mJawed** [comment]
Please remove default red on the submit button, default should be white

**Comment by Bhagyashrimane** [comment]
Looking fine.
