### ISSUE TITLE
Publish page, Embed on your site HTML textfield box size not able to expand.[Form-publish]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#109]
1. Publish page.
2. Embed on your site text field box.

Actual result-  Box size of Embed on your site not able to expand.

**Comment by mJawed** [comment]
Please remove default red on the submit button, defualt should be white

**Comment by mJawed** [comment]
Added min-height now not need to expand it

**Comment by charan-singh05** [comment]
We still need this box to be expandable when mouse is clicked over lower right side of the box and dragged down. We can keep maximum expanding limit to 5 lines along with the scroll bar.

**Comment by mJawed** [comment]
Added

**Comment by charan-singh05** [comment]
Issue fix verified.
