### ISSUE TITLE
Password and confirm password comparision validation message not showing properly.[Sign-up]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#11]
1.Enter Aaa111@12 in the password filed and then Enter Aaa111@23 in confirm password filed.
2.Then with confirm password shows validation message as like "Confirm Password is not matched".
3.Change the password entered in the password filed as Aaa111@12 to Aaa111@23.
4.Check the validation message with confirm password field.

Expected result- "Confirm password is not matched" validation message should disappear.

Actual result-"Confirm password is not matched"  validation message shows after correcting the password.

Check here-https://nimb.ws/lUMC2Y

**Comment by rohit-metagauss** [comment]
@Bhagyashrimane  This is fixed and deployed. Please test this.

**Comment by Bhagyashrimane** [comment]
Verified.
