### ISSUE TITLE
Entries page- without any submissions of the forms on entries not showing no records text not showing.[Form-entries]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#110]
1. Click on the form builder.
2. Add some fields.
3. Click on the Entries page.

Actual result- Not showing any Text as like No records.

Note- For Form page view also if in any organization does not have any forms then on that page also No records text should show.

**Comment by rohit-metagauss** [comment]
@Jawed05 Please add this message styling.

**Comment by mJawed** [comment]
@rohit-metagauss styling done, please add conditions, error only appears when no records found.

**Comment by charan-singh05** [comment]
Issue fix verified.
