### ISSUE TITLE
When control comes from Entries page to Form build page in dropdown of forms showing one form only.[Form-build]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#111]
1. Form the build page and add some fields.
2. Click on the entries page.
3. select one form from the dropdown of the forms.
4. Then click on Build.
5. Observe the form dropdown.

Actual result- In the dropdown showing one form only which selected in the Entries page.
Other forms not showing in the dropdown.

**Comment by rohit-metagauss** [comment]
@Bhagyashrimane Please re-test this.

**Comment by Bhagyashrimane** [comment]
Looking fine.
