### ISSUE TITLE
Toggle field related issue. [Form-build]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#116]
1. when checked the collect payment checkbox not showing  the line payments options.
2. Toggle pre-defined labels alignment not showing on proper at frontend.

**Comment by rohit-metagauss** [comment]
@Jawed05 JS part is completed for this issue.

**Comment by mJawed** [comment]
Label alignment fixed.

**Comment by charan-singh05** [comment]
When you click on "Collect Payment", the resulting options for fields underneath it are all misaligned.

**Comment by mJawed** [comment]
Fixed

**Comment by charan-singh05** [comment]
Still persists.

**Comment by charan-singh05** [comment]
Issue fix verified.
