### ISSUE TITLE
Form opened in popup when clicking on Entries->>New Entry alignment not proper.

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#117]
1. click on entries.
2.  click on New entry.

Actual result- from popup window alignment not looking proper.
Check here-
![image](https://user-images.githubusercontent.com/77260614/132637543-b80cee53-2428-4191-b478-07d01533e7fe.png)

**Comment by charan-singh05** [comment]
Issue fix verified.
