### ISSUE TITLE
Tab key not coming on "I have read and accepted Terms & Conditions" checkbox.[Sign-up]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#12]
1.Tab key is not coming on the "I have read and accepted Terms & Conditions" checkbox.
2.It goes directly on the Terms & Conditions link after the Organization field.

Check here-https://nimb.ws/Z356PM

Note- In the Sign-up page design "I have read and accepted Terms & Conditions" content.
           In Sign-up build "I have read and accepted Terms & Conditions true" content.
           After clicking on the "true" word checkbox selected.

**Comment by mJawed** [comment]
Fixed

**Comment by Bhagyashrimane** [comment]
When the Tab comes on Terms and condition checkbox Enter key not working means when Tab key control comes on Checkbox and press the Enter key then checkbox not got selected.

**Comment by mJawed** [comment]
Ad discussed this checkbox is a bootstrap issue,

**Comment by Bhagyashrimane** [comment]
As discussed with Jawed, looking fine then.
