### ISSUE TITLE
Time field alignment not proper when changes the size.[Form-build]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#121]
The time field is not proper when changes the size of the field.
check here-
![image](https://user-images.githubusercontent.com/77260614/132646257-906ff93e-7132-4d02-8404-9ece52481a33.png)

**Comment by mJawed** [comment]
Fixed

**Comment by charan-singh05** [comment]
Issue fix verified.
