### ISSUE TITLE
Created a new non-admin user and logged in with it. But it is showing me whole lot of data for super admin.

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#122]
Scenario-
1. Login with superadmin.
2. and Logout from the site.
3. Login with another user like the non-admin users.
4. Then check the organization dropdown.

Actual result- In the organization dropdown showing superadmin organization when we are logged in with non-admin user and able to see all the forms of superadmin organization.

**Comment by hunny-metagauss** [comment]
@rohit-metagauss - Please check this issue. I didn't the cause of the issue

**Comment by charan-singh05** [comment]
Issue was due to state not being managed for the relevant point. Fixed and verified.
