### ISSUE TITLE
Filter Pop-up Placing Issues

### ISSUE THREAD

**Issue by charan-singh05** [MetagaussInc/Blazeforms-Revamped-Frontend#124]
1- When filter pop-up is opened up, it doesn't close by itself if you click outside anywhere on the page.

2- Try searching for folder having only one entry. The pop-up and footer will be all misaligned. On smaller screen, bottom half of the filter pop-up won't even be visible.

3- Open the Filter pop-up. Hover the cursor over the folder or sub-folder name. The cursor will change into text entry type instead of selection type (hand cursor)

**Comment by mJawed** [comment]
Fixed

**Comment by charan-singh05** [comment]
Issue fix verified.
