### ISSUE TITLE
Design Issues

### ISSUE THREAD

**Issue by charan-singh05** [MetagaussInc/Blazeforms-Revamped-Frontend#129]
**Issue One**
 (Jawed)
On Enterprise page, when you click on "Columns" button, we should not see an empty check-box:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/81736010/132983223-d1164431-dcf7-49c8-9a8b-6a946dbb397c.png)

**Issue Two**
(Jawed and Rohit)
When no columns are selected (e.g, user removes all the check-box selections), We should see just see empty page instead of rows of empty check-boxes:
 
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/81736010/132983245-85c353dd-44a2-4a87-8e85-6e9db4294fed.png)
 

**Issue Three**
 (Rohit)
Even when I have made some entries for any form, I am seeing message at end of the table: "No Records found !"
 
Please fix this. The message should only display when there are actually no entries in the table. Also fix the spellings/sentence to: "No records found!"
 
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/81736010/132983261-2e990ed7-a453-4f4a-aa48-9340a8345116.png)

  
**Issue Four**
 (Jawed)
Page Break Issues: go to form builder, and add couple of page breakers
 
i) problem 1: multiple clicks are required on page break to get it selected. Its kind of VERY difficult to access its properties
 
ii) problem 2: naming/labelling of the page breaks isn't working right. Just try to add two to three page breaks and try renaming them 
 
iii) after publishing the form with multiple page-breaks, all page break tabs have same name "One" and not user definer names
 
iv) Back and Next buttons on tabs after publishing the page do not have any space in-between
 
v) launch icon for form has still not been updated.
 
![MicrosoftTeams-image 6](https://user-images.githubusercontent.com/81736010/132983292-8681fe76-38ae-4372-b1c6-eaf60f34670a.png)

**Issue Five**
 (Rohit)
After we set b/g image for the form, it cannot be removed. Need a "Clear" button, that can remove any added image. Also, max image size should be 500 KB. I didnt test the scenario with heavy image because last time I did it I was unable to access my ID. I know Rohit has already applied limit for Org branding page and updated me that it was applied for elsewhere too, but please double check it.
 
Also, selected image is applied immediately after we browse to it. Instead, it should first get selected on browse, and there should be "Apply" button that actually sets it in the b/g.

**Issue Six**
(Jawed)
On "Add Workflow" page: add tooltips, and change hover cursor for icon for action items to selection (right now its text)

**Comment by mJawed** [comment]
All points are covred.
