### ISSUE TITLE
Submit button not working as exprected.[Forgot-password]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#13]
1.Without entering any email address in the text field able to click on submit button.
2.Submit button showing by default highlighted.
3. After clicking on submit button page redirects to the Login page.
Check here-https://nimb.ws/1LOtgl
4. When clicks on submit button in console showing error.
Check here
![image](https://user-images.githubusercontent.com/77260614/127261742-b921f124-d7c3-41dc-a91a-1c295b1b0239.png)

**Comment by rohit-metagauss** [comment]
@Bhagyashrimane  This is fixed and deployed. Please test this.

**Comment by Bhagyashrimane** [comment]
Verified.
