### ISSUE TITLE
Usage Stats for Users Exceeding Allowed Limit

### ISSUE THREAD

**Issue by charan-singh05** [MetagaussInc/Blazeforms-Revamped-Frontend#131]
If you select organisation "PMd" for user charan.singh05@protonmail.com, you will see that in "Current Usage stats, number of users are being shown as 13/10". That means that actual number of users exceed those allowed by the plan, if high priority issue. Also, there is another catch.. I counted and found that number of users are 8 or thereabouts. Need to check the workflow what is going on here.

**Comment by hunny-metagauss** [comment]
this is because of the downgrading of the current plan.

**Comment by charan-singh05** [comment]
User should not be allowed to select lower tier plans than the one they have.

**Comment by hunny-metagauss** [comment]
done

**Comment by charan-singh05** [comment]
Issue fix verified.
