### ISSUE TITLE
Custom Roles And Organization Permissions

### ISSUE THREAD

**Issue by charan-singh05** [MetagaussInc/Blazeforms-Revamped-Frontend#132]
**Issue One:**

When using custom role. Select all "View" options. Assign custom role to invited user. When invited user logs in, they are unable to access any forms or workflows. This should be the case only when "View" option is not selected for Organization. 

**Issue Two:**

When a custom role associated with any of the invited users is deleted, it should show message: "This role is associated with one or more users. To delete it, remove the association(s) first."

**Issue Three:**

Analyze the "Upload" permissions option for Users and Organizations. Remove it for "Plan"

**Issue Four:**

When "View" option is the only one selected for any Role, all invited users with that Role should not be able to access "Add Organization" button, and also should not be able to make changes to "General", "Account Settings", and "Branding" tabs.

**Issue Five:**

When "View" option is the only one selected for Roles, the invited users are not able to see "Edit" and "Delete" icons for the forms.

**Comment by charan-singh05** [comment]
1- With View only access to Org, I am still able to make changes in "Account Settings" tab
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/81736010/133358998-50403109-0a83-414b-8948-66f4483044f7.png)


2- When trying to delete Role associated with invited user, the message I get is:
 
Success!
Role will not be deleted as this is already assigned to the user
 
"Success" word is a problem. Change it to:
Operation Not Allowed!
Role will not be deleted as this is already assigned to currently active user of this organisation.
 
 
3- If only View permission is allowed for Forms under any Role, it should take away "Build" and "Publish" tags from the Forms page for the invited user. These options appear when mouse is hovered over the listed forms. 
 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/81736010/133358953-0920e749-7803-4547-afe0-4b8821a49575.png)

**Comment by hunny-metagauss** [comment]
All issues fixed.

only Analyze the "Upload" permissions option pending. give me some time for this

**Comment by charan-singh05** [comment]
Issue fix verified.
