### ISSUE TITLE
Workflow related issue.

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#137]
1. Registration- While doing new registration and changed the plan then recaptcha disappears.
Without recaptcha also able to sign up.
![image](https://user-images.githubusercontent.com/77260614/133625748-8df7bf6c-e54f-4f51-bcbc-07fc61482c3a.png)

2.While registering new user and choose the plan then like $12 or $60 then account email activation mail got but when clicked on the link message shows like using free plan and not redirecting on billing point.
![image](https://user-images.githubusercontent.com/77260614/133630064-501ffa9d-a2ea-47c8-870e-3f71458b1d7b.png)

3.Form builder- 
Address field-address lines like address line1 , Address line2 ,Country etc when deselect one time and again try to select it is not showing checkbox checked showing unchecked but fields adding and deleting.
![image](https://user-images.githubusercontent.com/77260614/133631660-ef4efb40-383c-4f5a-bf86-721c125e65d4.png)

4.If form name is lengthy then in dropdown of the form on pages like form , Publish ,Entries alignment is not proper of the form name.
![image](https://user-images.githubusercontent.com/77260614/133632940-ada90f28-8789-430f-b12d-b4738c695abf.png)

5. Organization page- on organization branding page when uploading the Logo then upload button color showing blue when click on upload.

6. When sent the invitation for user from organization, Got the email but after clicking on the join organization button in the email then page not showing as like invitation accepted and URL also different.
![image](https://user-images.githubusercontent.com/77260614/133644287-fae06c8f-9bd0-4d56-93e3-1b99e7e2b276.png)

7.On Organization subscription page- newly changed plan history showing and trying to download the invoice of that plan. Invoice downloaded still button loader shows as like still loading.

**Comment by charan-singh05** [comment]
Issue fixes verified.
