### ISSUE TITLE
User permission pop-up cross close button not working.[Form]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#16]
1.Open Form page.
2.Click on permission.
3.Click on the cross sign to close the popup.

Expected result- When click on the cross sign close button popup should close.

Actual result- When click on the cross sign close button popup does not close.
Check here-https://nimb.ws/lSE97o

**Comment by rohit-metagauss** [comment]
@Bhagyashrimane This is fixed and deployed. Please check this.

**Comment by Bhagyashrimane** [comment]
Verified.
