### ISSUE TITLE
Edit option in user permission pop-up not working as expected.[Form]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#17]
1.Open form.
2.User permission popup.
3.Add the users.
4.Click on edit option one of the users.

Expected result-When click on one of the users edit options then able to edit that user only.

Actual result-When click on the edit option one of the users then all users edit option showing editable.
Check here-https://nimb.ws/asRKqD

**Comment by rohit-metagauss** [comment]
@hunny-metagauss Please check this.

**Comment by hunny-metagauss** [comment]
fixed

**Comment by Bhagyashrimane** [comment]
Functionality working fine.
1. But the button colors for all checkboxes showing blue.

**Comment by mJawed** [comment]
Fixed.

**Comment by Bhagyashrimane** [comment]
Still showing the blue color for buttons.

**Comment by mJawed** [comment]
Done

**Comment by charan-singh05** [comment]
Issue fix verified.
