### ISSUE TITLE
In search field, able to search the folders also with forms.[Form]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#18]
Expected result-In search field, forms are able to search only.

Actual result- In the search field, with forms able to search the folders also.
Check here-https://nimb.ws/5RhlAI

**Comment by rohit-metagauss** [comment]
@Bhagyashrimane This issue is fixed and Please test this.

**Comment by Bhagyashrimane** [comment]
1. Looking fine. Only Forms able to search. 
2. But the searching form in the hided list then form not shows the folder with browse all forms link. This link need to expand then shows the form.
check here-
![image](https://user-images.githubusercontent.com/77260614/132318860-4e26c048-2e17-4ab5-88e4-33a9164c4e71.png)

**Comment by rohit-metagauss** [comment]
@Bhagyashrimane Above pointer is fixed and deployed.

**Comment by charan-singh05** [comment]
Issue fixed and verified.
