### ISSUE TITLE
In Form Move, in search field placeholder as search folder should show.[Form]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#20]
1.Open the form and click on Move.
2.Click on the dropdown and see the search field.

A placeholder will be there to search the folder.
Check here-
![image](https://user-images.githubusercontent.com/77260614/127454450-d93bf342-6b09-4dd6-96b9-8d3450cdfc89.png)

Note-Change the Label of the dropdown.

**Comment by mJawed** [comment]
Fixed.

**Comment by Bhagyashrimane** [comment]
Looking fine.
