### ISSUE TITLE
When move the form to another folder then moved form not showing in selected folder need to refresh the page to see the changes.[Form]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#21]
1.Open the form and select the form to move.
2.Move the form to another folder.

Expected result-When moved any form to another folder then that form movement update automatically.

Actual result- When moved the form to another folder then when refreshing the form page then updates showing and form showing in a changed folder.

Check here-

**Comment by rohit-metagauss** [comment]
@Bhagyashrimane This is fixed and deployed. Please check this.

**Comment by Bhagyashrimane** [comment]
Verified.
