### ISSUE TITLE
In delete Popup window the selected form should show in bold or highlighted form.[Form]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#22]
1. Click on the delete to delete the form.
 
Form name should be in bold or in highlighted format to know that which form deleting.
Check here-
![image](https://user-images.githubusercontent.com/77260614/127457975-ca39dbff-068c-42fc-b731-d7304c530afc.png)

**Comment by mJawed** [comment]
Fixed.
