### ISSUE TITLE
Same user able to select multiple times in user permission.[Form]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#23]
The same user is able to select multiple times from user permission.
Check here-
![image](https://user-images.githubusercontent.com/77260614/127462374-4c83afd8-47c2-4499-9366-c540faa3269c.png)

**Comment by hunny-metagauss** [comment]
fixed

**Comment by Bhagyashrimane** [comment]
Working fine.
