### ISSUE TITLE
When deleting the user the form user permissions then not deleted properly.[Form]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#24]
1.Delete the user from the form user permission popup.

Expected result-When delete one user from the user permission popup then all data should delete related to that user.

Actual result- When deleted the user from the user permission popup then checkboxes related to that user showing on-page.
Check here-https://nimb.ws/5RhlAI

**Comment by rohit-metagauss** [comment]
@hunny-metagauss Please check this.

**Comment by hunny-metagauss** [comment]
fixed

**Comment by Bhagyashrimane** [comment]
steps-
1. Forms page and click on permission of the forms.
2. Add the user and give permissions to the user like view, delete, edit.
3. Edit the given permissions to the user 
4. for 1st time saving the updates but 2nd time when edits permissions do not save.
5. Means it is one-time permissions given to update.
6. View option on staging site, not editable.

**Comment by hunny-metagauss** [comment]
fixed

**Comment by Bhagyashrimane** [comment]
Working fine.
