### ISSUE TITLE
Enter key not working as expected with forgot-password and Sign-up page.

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#25]
1.Fill in all data on the Sign-up page.
2.Press Enter Key.

Expected result- After Filling all data on the sign-up page and press Enter Key the form should be able to submit.

Actual result-After filling the data on sign-up page then after pressing Enter key not able to submit the form.

**Comment by Bhagyashrimane** [comment]
@hunny-metagauss For Forgot password page please fix Enter key related issue.

**Comment by hunny-metagauss** [comment]
fixed

**Comment by Bhagyashrimane** [comment]
1. For forgot password page Enter key working fine.
2. For Sign up page not Enter key not working.

**Comment by hunny-metagauss** [comment]
fixed

**Comment by Bhagyashrimane** [comment]
Looking fine.
