### ISSUE TITLE
Scroller option we can give for showing the list of Organization on Work-Spaces Page.[Work-spaces]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#27]
1.Scroller option we can give for showing the list of Organization on Work-Spaces Page.
2.Now the list is looking like this-
Check hre-https://nimb.ws/BbNIEr

**Comment by mJawed** [comment]
@hunny-metagauss, As discussed with charan Sir on call, Please add Pagination.

**Comment by hunny-metagauss** [comment]
Added pagination and search autoseggestion

**Comment by Bhagyashrimane** [comment]
1. For search auto-suggestions- when searching any organization then deleted that search but the list still shows and then click on outside the page anywhere then it closes.
2. For pagination- when clicking on the 2nd-page button or any button the positions of the buttons change.

**Comment by hunny-metagauss** [comment]
@Jawed05  first point done. Please check second point

**Comment by mJawed** [comment]
Fixed pagination issue

**Comment by Bhagyashrimane** [comment]
Looking fine.
