### ISSUE TITLE
On delete popup window, cross (X) sign to close popup showing square box on that sign.[Work-spaces] 

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#28]
1.Login on the workspaces page.
2.Click on the delete option.
3. See the cross sign(X) to close the popup on the delete popup window.

Actual result- Showing square box on a cross (X) sign to close the delete popup window.
Check here-
https://nimb.ws/Tf9FYr

**Comment by mJawed** [comment]
Fixed.

**Comment by Bhagyashrimane** [comment]
Looking fine.
