### ISSUE TITLE
Close link and Close button (X) not working.[Work-spaces]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#29]
1.Click on delete the organization.
2.Pop-up opens.
3.Click on close buttons.

Actual result- Not able to close the popup when clicked on the close buttons.
Check here-https://nimb.ws/rElA5T

**Comment by hunny-metagauss** [comment]
fixed

**Comment by Bhagyashrimane** [comment]
Working fine.
