### ISSUE TITLE
Able to copy paste the password.[Login-page]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#3]
1.Copy the password from the notepad.
2.Paste that in the password field.

**Expected result**-Password should not be able to copy-paste in the field.
**Actual result**-Able to copy-paste the password.

Check here-https://nimb.ws/itCEKW

**Comment by rohit-metagauss** [comment]
@hunny-metagauss Please check this.

**Comment by hunny-metagauss** [comment]
fixed

**Comment by rohit-metagauss** [comment]
@Bhagyashrimane This is fixed and deployed. Please test this.

**Comment by Bhagyashrimane** [comment]
@hunny-metagauss Able to copy paste the password from password field to notepad.

**Comment by hunny-metagauss** [comment]
fixed

**Comment by Bhagyashrimane** [comment]
Looking fine.
