### ISSUE TITLE
When organization deleted from list then organization not deleted properly.[Work-spaces]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#30]
1.Click on delete.
2.Still the Organization was deleted showing in the list.
3.Refresh the page then the organization is deleted.

Expected result- When deleted any organization then it disappears from the list immediately.
Actual result- When deleted the selected organization from the list then not deleted directly still shows in the list. After refreshing the page the deleted organization disappers.
Check here-https://nimb.ws/qSn9ZY

**Comment by hunny-metagauss** [comment]
fixed

**Comment by Bhagyashrimane** [comment]
When the organization is deleted then showing the page loader and the organization list appears. But taking a little more time to load almost 10 to 12 sec.

**Comment by hunny-metagauss** [comment]
This depends on the server response time

**Comment by Bhagyashrimane** [comment]
Then Ok.
