### ISSUE TITLE
Content font size changes on delete popup window.[Work-spaces]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#31]
1.Login and click on the delete option and see the content on the delete popup.
Check here-
![image](https://user-images.githubusercontent.com/77260614/128144669-594ade2f-bc42-4771-8db0-ce780f5ec6b2.png)

2.After some time looks like the font size of the content chnaged like after refreshing the page.
Check here-
![image](https://user-images.githubusercontent.com/77260614/128144808-9e806389-d240-4af3-b292-f4081f5dae7e.png)

**Comment by mJawed** [comment]
Fixed.

**Comment by Bhagyashrimane** [comment]
looking fine.
