### ISSUE TITLE
Content showing on delete popup ? mark is missing.[Work-spaces]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#32]
Content on delete popup **"?"** mark is missing.
Check here-
![image](https://user-images.githubusercontent.com/77260614/128148523-4f464011-eeb4-4968-862f-a854db7d5194.png)

**Note**- A deleted organization name can be shown in highlighted or bold format.

**Comment by hunny-metagauss** [comment]
fixed

**Comment by Bhagyashrimane** [comment]
Looking fine.
