### ISSUE TITLE
For search box, when enter Space button once then also showing search results.[Work-spaces] 

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#33]
1.Press space one time only in the search box.
2.Observe the list.

Expected result- Not able to show any results of a search when pressing the space key.

Actual result- When press the Space key once then showing some lists results.
Check here-https://nimb.ws/VkBb3L

**Comment by hunny-metagauss** [comment]
fixed

**Comment by Bhagyashrimane** [comment]
Working fine.
