### ISSUE TITLE
When click on General showing error in console.[Manage-work-spaces]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#35]
1.Manage work spaces page.
2. Click on General.
 Actual result- Showing error in console when clicking on General.

Check here-
![image](https://user-images.githubusercontent.com/77260614/128321584-782fbd44-0879-4d88-967e-247f149efdde.png)

**Comment by hunny-metagauss** [comment]
fixed

**Comment by Bhagyashrimane** [comment]
Looking fine.
