### ISSUE TITLE
Password and confirm password comparision validation message not showing properly.[Manage-work-spaces]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#36]
1.Enter Aaa111@12 in the password filed and then Enter Aaa111@23 in confirm password filed.
2.Then with confirm password shows validation message as like "Confirm Password is not matched".
3.Change the password entered in the password filed as Aaa111@12 to Aaa111@23.
4.Check the validation message with confirm password field.

Expected result- "Confirm password is not matched" validation message should disappear.

Actual result-"Confirm password is not matched"  validation message shows after correcting the password and Add Organization button also not showing clickable i.e. not showing highlighted

Check here-https://nimb.ws/Oznlps

**Comment by hunny-metagauss** [comment]
fixed

**Comment by Bhagyashrimane** [comment]
1. Login with superadmin.
2. click on add organization and fill all the data in the form.
3. Add organization button not highlighted and not clickable.

**Comment by hunny-metagauss** [comment]
fixed

**Comment by Bhagyashrimane** [comment]
Looking fine.
