### ISSUE TITLE
Any Random string accepting in the email field.[Manage-work-spaces]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#38]
When new creating organization,
Expected result- Any random string not able to accept in the email id field.

Actual result-Accepting any random string in the email field.

**Comment by hunny-metagauss** [comment]
fixed

**Comment by Bhagyashrimane** [comment]
When creating a new organization still accepting any random string in the email field.
e.9.abc@gmail....com

**Comment by hunny-metagauss** [comment]
fixed

**Comment by charan-singh05** [comment]
Issue fix verified.
