### ISSUE TITLE
Showing error in console when click on Email text .[Login-page]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#4]
Click on the Email text.
Showing error in console.
Check here-https://nimb.ws/DYNwP6

**Comment by rohit-metagauss** [comment]
@hunny-metagauss Please check this.

**Comment by rohit-metagauss** [comment]
@hunny-metagauss Please check this.

**Comment by hunny-metagauss** [comment]
fixed

**Comment by rohit-metagauss** [comment]
@Bhagyashrimane This is fixed and deployed. Please test this.

**Comment by Bhagyashrimane** [comment]
Verified.
