### ISSUE TITLE
When refresh the page of manage workspace then control comes on workspaces page (Organization list).[Manage-workspaces]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#42]
1.Login and click on any one organization.
2.come on any page like Account settings.
3.e.g. Add one Stripe account and and refresh the page.

Expected result- when refresh the page control holds on the same page which is using.

Actual result-When refresh the page control goes on workspace page-

Check here-https://nimb.ws/36gBqM

**Comment by rohit-metagauss** [comment]
@charan-singh05 Added fix for this. Please check this.

@hunny-metagauss Changed Gaurd for the manage work spaces  -- FYI.

**Comment by charan-singh05** [comment]
Issue fix verified.
