### ISSUE TITLE
When selected the country then automatically not selecting the currency in the currency fields.[Manage-work-spaces]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#45]
1.Staging site- When we select the the country in the field then currency automatically integrate.
Check here-https://nimb.ws/lg19ew
2.On Revamp - When selected the country in the country field currency not integrates automatically.
Check here-https://nimb.ws/6Yb5Be

**Comment by hunny-metagauss** [comment]
fixed

**Comment by Bhagyashrimane** [comment]
Working fine.
