### ISSUE TITLE
General page, Organization field not showing placeholder.[Manage-work-spaces]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#46]
1.Login and click on the organization.
2.Control comes on the General page.

Actual result- Not showing the placeholder in the Organization field.
Check here-
![image](https://user-images.githubusercontent.com/77260614/130558667-6347770e-5487-4f63-a36b-3001bdc99577.png)

**Comment by hunny-metagauss** [comment]
done

**Comment by Bhagyashrimane** [comment]
Looking fine.
