### ISSUE TITLE
Account settings- placeholder in search field not proper and label of add button also.[Manage-work-space]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#47]
Placeholder in search field not looking proper and add button label also not proper.
Check here-
![image](https://user-images.githubusercontent.com/77260614/130601443-08db0b1e-339f-4f05-8b57-a062c439e1ac.png)

**Comment by hunny-metagauss** [comment]
done

**Comment by Bhagyashrimane** [comment]
Looking fine. Compared with HTML provided.
