### ISSUE TITLE
When edit stripe account button label is not proper and buttons not showing clickable.[Manage-work-space]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#48]
1.When edit stripe account showing update button on staging site. 
2.But on Revamp site showing Save button.
3.Edit and delete buttons not showing clickable.
Check here-
Staging site
![image](https://user-images.githubusercontent.com/77260614/130608328-51c3bc80-a217-4e56-9b0c-5b9e3c2ccd4c.png)

Revamp site-
![image](https://user-images.githubusercontent.com/77260614/130608412-0a08553b-c40b-43ef-bc89-cfb3c4a6cecb.png)

**Comment by hunny-metagauss** [comment]
@mJawed  Cursor pointer on edit and delete button

**Comment by mJawed** [comment]
Added

**Comment by Bhagyashrimane** [comment]
Looking fine.
