### ISSUE TITLE
Search field not working properly when given space only.[Manage-work-space]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#49]
1. Click on search filed.
2.Click on the space button.
3.Now Click anywhere on the page.

Expected result - When clicking on anywhere on the page then the list should show.

Actual result- When clicking on the page then the list not showing.
Check here-https://nimb.ws/uAb4Iv

Note-Check all the search fields.

**Comment by hunny-metagauss** [comment]
fixed

**Comment by Bhagyashrimane** [comment]
Looking fine.
