### ISSUE TITLE
Their is no limit for unsuccessful login attempts.[Login-page]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#5]
1.Enter invalid Email and password combinations.

Expected result-Their should be a limit on the total number of unsuccessful login attempts. So that a user should not be able to try all possible combinations of Email-password.
Actual result-There is a limit on the total number of unsuccessful login attempts. So that a user is able to try all possible combinations of Email-password.

Check here-https://nimb.ws/AJaHx9
**Note-Three login attempts at max.**

**Comment by hunny-metagauss** [comment]
Maximum 5 login attempts set. The condition is now based on the browser.

**Comment by Bhagyashrimane** [comment]
There are 3 limits for the unsuccessful login attempt. Working fine.
