### ISSUE TITLE
On header of anywhere on page should show plan details bar.

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#52]
After login when the user redirects to the form page or any page then the plan details bar should show.

Check here-
![image](https://user-images.githubusercontent.com/77260614/130617033-e3d037a2-35c7-4d68-b5d3-b33f59306c4a.png)

**Comment by hunny-metagauss** [comment]
Done from my end. Design pending.

**Comment by mJawed** [comment]
Fixed.

**Comment by Bhagyashrimane** [comment]
1. View details link on the plan not redirecting on the organization subscription page.
2. Cross sign to close the plan details not showing clickable.
Check here-
![image](https://user-images.githubusercontent.com/77260614/132201344-df3eb272-9794-41a6-ae23-6be0a58b1fd6.png)
3. Subscription status also not showing clickable after closing the details plan.
Check here-
![image](https://user-images.githubusercontent.com/77260614/132201384-da63322a-e4f2-436b-8465-3e86c34aecf9.png)

**Comment by mJawed** [comment]
Fixed

**Comment by Bhagyashrimane** [comment]
View details link on the plan not redirecting on the organization subscription page.

**Comment by hunny-metagauss** [comment]
fixed

**Comment by charan-singh05** [comment]
Issue fix verified.
