### ISSUE TITLE
When click on the edit button then button label is showing save instead of Update.[Manage-work-space]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#53]
1.User page and click on the edit button.
2.Check the button label of the Edit popup.

Actual result- When Edit popup window then button label showing save instead update.
Check here-
![image](https://user-images.githubusercontent.com/77260614/130747486-4ad23e1f-c168-46e7-958e-097a29d4ae66.png)

**Comment by hunny-metagauss** [comment]
This is same as the staging panel. Please verify.

**Comment by Bhagyashrimane** [comment]
verified with staging looking fine.
