### ISSUE TITLE
When click on the organization then taking time to open the manage-work-space page.[Manage-work-space]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#54]
1.Click on the one of the organization
2.Observe the page loading time.

Actual result- When click on the organization than taking time to load the page that's why a user's details filled in the field not showing immediately looking like nothing filled.

**Comment by hunny-metagauss** [comment]
It depends on the server response time. When we add page loader this delay will not looking odd.

@mJawed  Please provide page loader.

**Comment by mJawed** [comment]
@hunny-metagauss Add inline loader for now, we update it once Vikram sir provided.

**Comment by Bhagyashrimane** [comment]
Looking fine.
