### ISSUE TITLE
The content provided in delete popup not looking proper.[Manage-work-space]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#55]
All delete pop-ups on the Manage-work-space page delete content not looking proper.
There should be "?" after the sentence is completed.
![image](https://user-images.githubusercontent.com/77260614/130761970-665b7741-8449-4454-9761-89bf9aec3fba.png)

**Comment by hunny-metagauss** [comment]
fixed

**Comment by Bhagyashrimane** [comment]
Looking fine.
