### ISSUE TITLE
On Roles page, Standard and Administrator information not showing and permissions module also not showing.[Manage-work-spaces]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#58]
1.Click on the Role page.
2.Check Standard and Administrator role.

Actual result-Not showing any info and permission checkboxes of the module of std and admin role.

Expected result-Standard and Administrator roles need to by default is given permissions and info.
Check here-
![image](https://user-images.githubusercontent.com/77260614/130789707-39c83ed3-c6d5-4ae2-9be9-71eab382b179.png)

Note-Not able to Save the info and then click on the Back button then control comes on the General page.

**Comment by hunny-metagauss** [comment]
fixed

**Comment by Bhagyashrimane** [comment]
1. Click on one of the organizations and go to the Roles page. Standard and Administration Roles permissions modules are showing editable.
2. Create a new role and click on the delete button of the newly added role or any role existing. Click on the cross button of the popup to close. But the created role is deletes from the list.

**Comment by hunny-metagauss** [comment]
fixed

**Comment by Bhagyashrimane** [comment]
Looking fine.
