### ISSUE TITLE
On Subscription page- consumed storage showing long decimal number.[Manage-work-space]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#59]
Actual result-On the subscription page, the consumed storage data showing in long decimal.

Expected result-It should show in Approximate value so it will be more understandable.

Check here-
![image](https://user-images.githubusercontent.com/77260614/130790518-d0f3786d-01b1-4a7e-bcc9-89ef29f1d4f6.png)

**Comment by hunny-metagauss** [comment]
fixed

**Comment by Bhagyashrimane** [comment]
Looking fine.
