### ISSUE TITLE
When click on password hide/show icon then cross mark not coming on that icon.[Login-page]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#6]
1.Login and enter a password.
2.Click on the hide/show icon.

Expected result- When click on password hide/show icon then cross mark should show on icon to show the password.

Actual result-Cross mark not coming on hide/show icon when clicked on the icon to show the password.
Check here-https://nimb.ws/ncUGQA

**Comment by rohit-metagauss** [comment]
@hunny-metagauss Please check this.

**Comment by hunny-metagauss** [comment]
We do not have this kind of feature right now. 
@Bhagyashrimane - This is the Microsoft Edge browser default feature. Please verify on other browsers as well.

**Comment by rohit-metagauss** [comment]
@Bhagyashrimane This is fixed and deployed. Please check this.

**Comment by Bhagyashrimane** [comment]
With Microsoft Edge Cross mark showing when hide/show password.
