### ISSUE TITLE
When click on to change the plan then slider of plans opens but they not working properly.[Manage-work-space]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#60]
1.Click on the subscription page.
2.Click on change plan

Expected result- When click on the change plan then sliders should show and after choosing the plan billing page should open.

Actual result - when clicking on the change plan the slider of plans opens but does not work properly and the billing page also not open when choosing a plan.

**Comment by hunny-metagauss** [comment]
done

**Comment by Bhagyashrimane** [comment]
Redirecting on the billing page.
