### ISSUE TITLE
Referal program page- Refer a friend window not showing the mandatory fields mark and button labels also different.[Manage-work-space]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#61]
Referral programs Page-
1.Click on message - Refer a friend window- All fields showing the mandatory mark in staging but on revamp not showing the mandatory marks with fields.
2.Button labels are also different.
Staging site-
![image](https://user-images.githubusercontent.com/77260614/130831147-391632ae-0f5f-442a-8a18-5530b9c7ea0d.png)

Revamp site-
![image](https://user-images.githubusercontent.com/77260614/130831318-9677fd09-2dbf-48bb-86ec-0b0da21979f0.png)

**Comment by hunny-metagauss** [comment]
fixed

**Comment by Bhagyashrimane** [comment]
1. Mandatory fields signs showing and button labels also looking fine.
2. But able to type any random string in the To-email field and not showing any validation message.

**Comment by hunny-metagauss** [comment]
fixed

**Comment by charan-singh05** [comment]
Issue fix verified.
