### ISSUE TITLE
On Referral program page- for twitter showing the facebook logo.[Magae-work-space]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#62]
1.On referral program page- for twitter showing the Facebook logo.

**Comment by mJawed** [comment]
Fixed.

**Comment by Bhagyashrimane** [comment]
1. The alignment of the icons is not proper.
Check here-
![image](https://user-images.githubusercontent.com/77260614/132279791-8546370c-f9d6-4d9c-8857-6da27d87163e.png)

2. On staging social icons showing like this-
![image](https://user-images.githubusercontent.com/77260614/132279895-e634bd4a-5c17-4c45-a56e-95206eeb5799.png)

**Comment by mJawed** [comment]
Alignment fixed, we will use a new design of social icons.

**Comment by charan-singh05** [comment]
Issue fix verified.
