### ISSUE TITLE
For uploading the image taking too much time to upload.[My-profile]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#63]
1.Login and click on My accounts
For uploading the image taking too much and continue to showing loading circle.

**Comment by hunny-metagauss** [comment]
there is 404 error in API. That's why

**Comment by hunny-metagauss** [comment]
fixed

**Comment by Bhagyashrimane** [comment]
Working fine.
