### ISSUE TITLE
When created new account then not showing the Avtar on profile like by default human image.[My-profile]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#64]
1. Create a new user and log in.
2. Check the My account and profile image.

Actual result-When created a new account and profile image not showing like Avatar.

**Comment by mJawed** [comment]
@hunny-metagauss Please add a profile pic functionally on the header.

**Comment by hunny-metagauss** [comment]
fixed

**Comment by Bhagyashrimane** [comment]
Looking fine.
