### ISSUE TITLE
Spelling mistake in confirm password and button lable color not looking proper.[My-profile]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#66]
Confirm password label and placeholders spelling not correct and Button label also not in the proper color.
Check here-
![image](https://user-images.githubusercontent.com/77260614/130834812-f18acd01-be8a-4425-a811-f37fbd61a430.png)

**Comment by hunny-metagauss** [comment]
fixed. Initially, the button will be disabled, that's why.

**Comment by Bhagyashrimane** [comment]
Looking fine.
