### ISSUE TITLE
When click on the image on left side of the page then showing dropdown to open My account and Logout.[My-profile]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#67]
Staging site- When the cursor comes on the image on the left side of the page then my account and logout option shows like hover.

Revamp site- Image on the left side of the page showing dropdown to opens the options like My account and Logout and showing dropdown arrow also.
Check here-
![image](https://user-images.githubusercontent.com/77260614/130835687-da18c1aa-67ee-489e-82f9-7df3d13d62d2.png)

**Comment by mJawed** [comment]
Fixed.

**Comment by Bhagyashrimane** [comment]
Looking fine.
