### ISSUE TITLE
Bulk Delete , Archive an Move options on forms page showing with filters not working.[Form-page-view]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#68]
Bulk delete, Archive, Move options not working and showing always highlighted without selecting forms.
Check here-
![image](https://user-images.githubusercontent.com/77260614/131119223-ac0f3b26-3272-42b5-8c78-06dd29432fa8.png)

**Comment by rohit-metagauss** [comment]
@Bhagyashrimane This issue is fixed and Please test this.

**Comment by Bhagyashrimane** [comment]
1.Bulk action Move and Archived icons interchanged as compared to staging site.
2. Bulk moves- Immediately not moving the forms when refreshing the page it will show the forms moved in the folder.
3. Bulk Archived-
 Steps-
a) select the forms 2 or more.
b) click on Bulk Archived
c)cancel the process
d)deselect one of the form
e)click on Bulk Archived
 Actual result - above steps followed then selected forms names not showing, in the popup showing random string.
Check here-
![image](https://user-images.githubusercontent.com/77260614/132277659-2f888d10-4c89-466c-b1f8-885ed8c85045.png)

**Comment by charan-singh05** [comment]
Issue fix verified.
