### ISSUE TITLE
When Star icon infront of the form not working proper and star ison & checkbox with each other not working proper.[Form-page-view]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#69]
1.Click on the star in front of the form.
2. Then to deselect the star icon in front of the form.
3. select the checkbox in front of the form and then select the star icon.

Actual result- Not able to deselect the star icon in front of the form and when checkbox selected of the form then selects the Star icon then checkbox automatically shows unchecked.

Note- That's why not able to check the bulk delete and other options.

**Comment by rohit-metagauss** [comment]
@Bhagyashrimane This issue is fixed and Please test this.

**Comment by Bhagyashrimane** [comment]
Still, the star features not working properly. 
1. When clicking on the star in front of the form and deselect it not showing immediately. When refreshing the page the star shows deselected.
2. When deselecting the Star then Checkbox also in front of the form also get unchecked.

**Comment by Bhagyashrimane** [comment]
Looking fine.
