### ISSUE TITLE
As soon as the login page opens, by default the cursor should remain on the email textbox.[Login-page]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#7]
1.Open the Login page.
 
Expected result- When opens the login page cursor by default should remain on the email textbox.

Actual result- When opens the login page cursor not remains on the email textbox

**Comment by rohit-metagauss** [comment]
@hunny-metagauss Please check this.

**Comment by hunny-metagauss** [comment]
fixed

**Comment by rohit-metagauss** [comment]
@Bhagyashrimane This is fixed and deployed. Please test this.

**Comment by Bhagyashrimane** [comment]
Verified.
