### ISSUE TITLE
Options in front of the form name like build , publish. Entried, URL not working.[Form-page-view]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#70]
Options in front of the forms like Build, publish Entries, URL not working.
Check here-
![image](https://user-images.githubusercontent.com/77260614/131121270-f0a6be72-e5b5-4ac1-8b8b-825f5979807a.png)

**Comment by rohit-metagauss** [comment]
@Bhagyashrimane This issue is fixed and Please test this.

**Comment by Bhagyashrimane** [comment]
Looking fine.
