### ISSUE TITLE
Logout button is not working on Form page.[Form-page-view]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#71]
Logout button not working on Form page.

**Comment by hunny-metagauss** [comment]
done

**Comment by Bhagyashrimane** [comment]
1. Click on the logout button, after successful logout on the login screen press the back button. It will show the login page.
Showing below page-
![image](https://user-images.githubusercontent.com/77260614/132339113-2b13d349-10c9-4425-a281-1829da23fc38.png)

**Comment by charan-singh05** [comment]
Issue fix verified.
