### ISSUE TITLE
Publish, Entries when click on them redirection not as expected.[Form-page-view]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#75]
1. When clicking on Publish page then redirect to on publish a page of the form.
Actual result- When click on the Publish link then control redirect to the build page.

2. When clicking on the Entries page then redirect to on Entries page of the forms.
Actual result- When clicking on the Entries page then the page not redirecting to the Entries page.

3. When clicking on the URL new tab, not opening. It is opening on the same page

**Comment by charan-singh05** [comment]
Issue fixes verified.
