### ISSUE TITLE
Timezone and Currency fields not working as expected.[Manage-work-space]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#77]
1. Add new organization and fill all the fields of the form as like timezone and Currency.
2. then save the organization.
3. Check the organization list organization added to the list.
4. then click on that added organization and check the timezone and currency fields.

Expected result- When click on the organization's newly added timezone and currency fields should show filled.

Actual result-When click on the newly added organization then timezone and currency fields showing empty when it is filled with when added the organization.

**Comment by hunny-metagauss** [comment]
fixed

**Comment by Bhagyashrimane** [comment]
Working fine.
