### ISSUE TITLE
Without enetring any data when adding the form then also able to save the form.[Form-page]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#78]
1. Login and click on Add form.
2. Add form popup shows.
3. fields are empty and click on the Save button.

Expected result- without filling in any data should not be able to save the form and redirect on the build page.

Actual result- Without filling in any data when adding the form on the popup of Add form able to save the form and redirecting on the build page.

Check here-https://nimb.ws/uc0aCU

**Comment by rohit-metagauss** [comment]
@Bhagyashrimane This issue is fixed.

**Comment by Bhagyashrimane** [comment]
Issue still appearing.

**Comment by Bhagyashrimane** [comment]
Working fine.
