### ISSUE TITLE
New form popup- Copy Existing form and Copy Existing workflow links not working.[Form-page]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#79]
1. Login and click on Add form.
2. New form popup opens. 
3. Observe the links Copy Existing form and Copy Existing workflow.

Actual result- Copy Existing form and Copy Existing Workflow links available below the Add Form and Add Workflow buttons not working.
Check here-
![image](https://user-images.githubusercontent.com/77260614/131618941-7e6032dd-8859-4eb9-8db2-fdb11446330d.png)

**Comment by charan-singh05** [comment]
Issue fixed.
