### ISSUE TITLE
Fields popover body- Delete, Duplicate , Make small ,Make Large fetaures not working properly.[Form-build]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#80]
1. Add form and come on the build page.
2. Drag and drop one field on the page.
3. Popover body appears.

Actual results- 
1. For Delete and duplicate options need to click many times on them to work properly. It is not having smooth working.
2. Make small and make bigger- when clicking on them fields are deleting.

**Comment by rohit-metagauss** [comment]
@Bhagyashrimane This issue is fixed.

**Comment by Bhagyashrimane** [comment]
Going to change the functionality. Instead of popover using three dots on the fields to see the popover.
