### ISSUE TITLE
change plan slider not lookig proper.[Manage-work-space]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#81]
1. Click on organization and click on Subscription
2. Click on the change plan and observe the slider.

Actual result- When clicked on change plan then showing the plans available slider but slider not looking proper.

**Comment by mJawed** [comment]
Fixed

**Comment by Bhagyashrimane** [comment]
1. Slider looking fine now. But Slide arrows and slides alignment not looking properly aligned.
2. Slider arrow not looking proper looking wide and looks not proper.

**Comment by mJawed** [comment]
Please check the slider demo https://swiperjs.com/demos, 
if want a change, please assign it to hunny.

**Comment by Bhagyashrimane** [comment]
Change plan slider looking fine as compared to Jawed provided the slider demo link.
