### ISSUE TITLE
For superadmin, new organization add form fields move when showing the validation messsage with that when not filled the content.[Manage-work-space]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#82]
1. Login with superadmin
2. Click on add organization.
3. Observe the Form.

Actual result-When not filled the data in the fields and when shows the validation message with fields then below fields position changes.

Check here-https://nimb.ws/tvqelk

**Comment by mJawed** [comment]
@hunny-metagauss Please add functionality as discussed.

**Comment by hunny-metagauss** [comment]
@Jawed05  I have added a class on validation messages as per our discussion. I also update on login, register, forgot password, add / edit organization. Please have a look and let me know if any additional pages you are required to add.

**Comment by mJawed** [comment]
Fixed.

**Comment by Bhagyashrimane** [comment]
Still moves the positions of the fields.

**Comment by mJawed** [comment]
Fixed.

**Comment by Bhagyashrimane** [comment]
Looking fine for all forms.
