### ISSUE TITLE
Payment field making conflict with other fields and control & properties also.[Form-build]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#83]
1. Login and add form.
2. Add other fields and Payment fields.
3. Check the behavior of the options.

Actual Scenario happening with payment field-
1. Add fields like First name, Last name with fields showing popover body like delete, duplicate, etc.
Control also moves automatically on properties.
2. Now add the payment field and now check the behavior of the controls and properties feature with click on other fields and also on the payment field.
3. Everything stops working like controls and properties.
4. Refresh the page and the first click on the field other than payment then control comes on properties then click on payment field. 

Other points to check with payment field-
1. Popover body also not showing with Payment field.
2. When added the Payment field then the field does not show on the build page. It will show when refreshing the page.
3. Line items, Subtotal, Amount Due- menus when clicked on them not showing options in the properties.
4. When an account is added which shows in the properties after clicking on the payment field. But that added account not showing the dropdown list of the Accounts.
Here-
![image](https://user-images.githubusercontent.com/77260614/131652532-c90980ee-d697-4f48-a45d-1222abfb5471.png)

**Comment by rohit-metagauss** [comment]
@Bhagyashrimane This issue is fixed.

**Comment by Bhagyashrimane** [comment]
1. When clicked on line items showing options in properties like Sub Total, Show Line Items, Map Billing fields these options checkboxes are not clickable.
2. Sub Total, Show Line Items, Map Billing fields this option shows in the form but checkboxes are unselected in the properties.
3. When clicking on the line items first then control not comes on properties. When clicking on the payment field and then click on line items then controls come on properties of the line items.
4. Amount also showing by default like 
![image](https://user-images.githubusercontent.com/77260614/131962387-ea8d9c3b-09db-4c3d-bfa3-c768768c9af3.png)

**Comment by rohit-metagauss** [comment]
@Bhagyashrimane Please check test this.

**Comment by Bhagyashrimane** [comment]
Working fine all issues.
