### ISSUE TITLE
Phone number and Number both fields functionality is same.[Form-build]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#84]
1. select the number and Phone number fields and observe the functionality of both fields.

Actual result- number and Phone number both the fields working as a number field and showing the increase and decrease arrows in the field.

**Comment by rohit-metagauss** [comment]
@Bhagyashrimane This issue is fixed.

**Comment by Bhagyashrimane** [comment]
Phone number field not showing on the publish page and On the Form URL also.
Number field looking fine.

**Comment by rohit-metagauss** [comment]
@Bhagyashrimane  This is fixed.

**Comment by Bhagyashrimane** [comment]
For the phone number field, there is not a proper validation for Us and international also.

**Comment by charan-singh05** [comment]
Issue fix verified.
