### ISSUE TITLE
After Publishing the form URL of the form not working.[Form-publish]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#85]
1. Form publish and check the URL on another page.

Actual result- After Publish the Form URL not working. Not showing form when using the URL.

**Comment by rohit-metagauss** [comment]
@Bhagyashrimane This issue is fixed.

**Comment by Bhagyashrimane** [comment]
Working URL-https://metagaussinc.github.io/Blazeforms-Revamped-Frontend/#/blazeforms/Main_Oraganization/Form222
URL on publish page-https://metagaussinc.github.io/#/blazeforms/Main_Oraganization/Form222---(not working)
