### ISSUE TITLE
When trying to go from build page to publish page showing error in console.[Form-build]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#86]
1. When redirecting from Form builder page to publish page in console showing the error
Check here-
![image](https://user-images.githubusercontent.com/77260614/131778754-8c882897-ef18-4a85-928f-dc8e361c7865.png)

**Comment by rohit-metagauss** [comment]
@Bhagyashrimane This issue is fixed.

**Comment by Bhagyashrimane** [comment]
No error in console.
