### ISSUE TITLE
Form name dropdown on form build page selected form not showing in the dropdown.[Form-build]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#87]
1. Select one form and go on the build page.
2. Check the left side dropdown of the form.
3. Select another form from the dropdown.

Actual result-When form selected from form listing that is not showing in the dropdown on build page and also when selected 
from the dropdown also not showing the selected form in the dropdown.

Note-underlined with black line.
Check here-
![image](https://user-images.githubusercontent.com/77260614/131792129-6c6b0b27-7412-419b-99ca-70c593727982.png)

**Comment by rohit-metagauss** [comment]
@Bhagyashrimane Please check test this.

**Comment by Bhagyashrimane** [comment]
Working fine on All pages like Build,Publish and Entries.
