### ISSUE TITLE
Form name dropdown arrow on form build page not showing properly.[Form-build]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#88]
1. Form builder page
2. form name dropdown click on the arrow.

Actual result-
1. When clicking on the form name dropdown then expands arrows movement not changes link upside or downside. It is showing in one upside only. 
2. Arrow and content alignment are also not proper.

Check here-
![image](https://user-images.githubusercontent.com/77260614/131796188-2572ff97-aa4c-4fb4-8a16-6494612fef51.png)

**Comment by mJawed** [comment]
Fixed.

**Comment by Bhagyashrimane** [comment]
Looking fine.
