### ISSUE TITLE
Fields and Popover of that fields overlapping not looking porper.[Form-build]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#89]
1. Form builder page.
2. drag and drop one field and observe the field popover

Actual result-Fields and fields popover overlapping. Also hiding the content of the fields.
When opens the when condition window also the field popover overlaps on that.
Check here-
![image](https://user-images.githubusercontent.com/77260614/131806559-c473a400-b407-4249-a1f2-2de0fd917ae7.png)

**Comment by mJawed** [comment]
Added ellipses for it

**Comment by rohit-metagauss** [comment]
@Bhagyashrimane Please check test this.

**Comment by charan-singh05** [comment]
Issue fix verified.
