### ISSUE TITLE
Email text field accepting random string instead of real email.[Sign-up]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#9]
1.Enter any random email in the text field.
example- name@122.165.1.1.aaa
      name..@gmail.com
      
Expected result-Email text field should accept a valid email id.

Actual result- Accepting any random string of email id.
Check here-https://nimb.ws/KAuhp0

**Comment by rohit-metagauss** [comment]
@Bhagyashrimane  This is fixed and deployed. Please test this.

**Comment by Bhagyashrimane** [comment]
Verified.
