### ISSUE TITLE
Cancel button on When condition  popup not working.[Form-build]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#90]
1. Go on the Form builder page.
2. drag and drop the field.
3. click on the When condition. 
4. Then the popup opens.

Actual result-When condition Popup cancel button not working.

Check here-
![image](https://user-images.githubusercontent.com/77260614/131835218-4c694bbb-6aca-4900-ac61-8738a22dec00.png)

**Comment by mJawed** [comment]
Fixed.

**Comment by Bhagyashrimane** [comment]
Looking fine.
