### ISSUE TITLE
All Notification popup-color combination not showing attractive.

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#91]
Notification popups like after updating or successful saving color of the popups not showing proper.
e.g.
![image](https://user-images.githubusercontent.com/77260614/131865172-da1502a8-571a-4952-aa2d-dd9d9bac1712.png)

**Comment by mJawed** [comment]
Fixed

**Comment by Bhagyashrimane** [comment]
As per discussion with Jawed, the Notification popup design is ok.
