### ISSUE TITLE
In Fields some options not having and some extra options not able to add.[Form-build]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#92]
1. Radio field- extra options added but name not updated immediately. It updates when clicking on somewhere on-page.
2. Rating field-Not able to add extra options, options alignment not proper, Rating options in properties like agree/disagree working same, All size options not available.
3. Address and Table field not available in the list of fields. On staging these options available.

**Comment by rohit-metagauss** [comment]
@Bhagyashrimane Please check test this.

**Comment by charan-singh05** [comment]
Issue fix verified.
