### ISSUE TITLE
Header on Login page not looking proper.[Login-page] 

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#93]
Scenario-
1. log in to the site.
2. without using that for some time like session timeout.
3. After some time user log out and then observe the login page.

Actual result- Header page after logout showing options like forms, organization, organization dropdown, profile image.

Check here-
![image](https://user-images.githubusercontent.com/77260614/131883373-fd205229-eb43-49c4-9bd7-3dcc381eee1d.png)

**Comment by hunny-metagauss** [comment]
@Bhagyashrimane  - I did some changes in the code regarding this. You need to check once.

**Comment by Bhagyashrimane** [comment]
Looking proper.
