### ISSUE TITLE
Add form popup-description field validation message not showing properly.[Form-view]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#94]
1. Click on Add form.
2. Description validation message not showing properly.

Check here-
![image](https://user-images.githubusercontent.com/77260614/131886135-67a7c799-b002-4bb7-92f1-36995e4690a1.png)

**Comment by rohit-metagauss** [comment]
@Bhagyashrimane Please check test this.

**Comment by Bhagyashrimane** [comment]
Looking fine.
