### ISSUE TITLE
View details related to plan bar color not looking proper like looking dark red.[Form-view]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#95]
The color of the bar not looking proper and the cross sign also not working. Not able to close the bar
Check here-
![image](https://user-images.githubusercontent.com/77260614/131886574-8a4cc91f-1428-4630-8e0d-db58879b3c02.png)

**Comment by mJawed** [comment]
Other things are done
@hunny-metagauss Please add close functionality.

**Comment by hunny-metagauss** [comment]
@mJawed  done. please check once

**Comment by Bhagyashrimane** [comment]
As per discussion with Jawed, the Color of the view details bar should be like this.
