### ISSUE TITLE
Dropdown arrow not showing on filter option.[Form-view]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#96]
check here-
![image](https://user-images.githubusercontent.com/77260614/131886776-9071f701-7945-44d5-afe2-7a18df072107.png)

**Comment by mJawed** [comment]
Fixed.

**Comment by Bhagyashrimane** [comment]
Compared with HTML provided by Jawed. Looking fine.
