### ISSUE TITLE
Same fields showing two times on the form.[Form-build]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#97]
1. Create the form and add some fields.
2. Click on publish and Use the URL to see the form.
3. Observe the form.

Actual result- Form fields showing two times after publishing the page and using the URL to see the form at the frontend.
Submit button also not showing on the form.
Check here-
![image](https://user-images.githubusercontent.com/77260614/131981191-a92f451f-8643-49fc-b18b-322069ce0563.png)

**Comment by rohit-metagauss** [comment]
@Bhagyashrimane Please check test this.

**Comment by Bhagyashrimane** [comment]
Looking fine.
