### ISSUE TITLE
Entries page-not looking proper and features also not proper.[Form-Entries]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#98]
1. Entries not able to check because of Published URL form not working properly.
2. Columns dropdown starts showing when there is some submission done on staging.
But on Revamp already showing the Columns dropdown.
In columns dropdown showing some fields like 
![image](https://user-images.githubusercontent.com/77260614/131991849-1d7d4c8a-80d3-47a5-b189-e91f9103d255.png)

3. In Actions dropdown delete option is not available.
4. On Entries unwanted checkbox showing not looking proper.

**Comment by rohit-metagauss** [comment]
@Bhagyashrimane Please check test this.

**Comment by Bhagyashrimane** [comment]
2nd issue still showing.

**Comment by charan-singh05** [comment]
Issue fixed and verified.
