### ISSUE TITLE
Login page related issue.[Login-page]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#99]
1. Make Login page email fields allow copy past.
2. In the email field when start typing the email and just type one letter like abc12@gmail.com and type "a" only then showing the validation message "Enter is required"
3. Password field- eye icon showing double please remove the one eye icon for Show/Hide.
Browser - Chrome
Check here-
![image](https://user-images.githubusercontent.com/77260614/132088705-a4ebc1d4-72a7-4338-863c-4f6e3f778240.png)

**Comment by hunny-metagauss** [comment]
@Bhagyashrimane  -  I am not able to see any eye icon in front of the password field. Check once your browser settings. Sometimes it depends on the browser.

Other issues fixed.

**Comment by Bhagyashrimane** [comment]
1st and 2nd issue working fine. 
3rd issue specific to browsers.
